version: '0.1'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER : postgres
       POSTGRES_PASSWORD : password
       POSTGRES_DB : postgres

    volumes:
      - postgres_data:/var/lib/postgresql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-backend:latest
    container_name: app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db



volumes:
  postgres_data:
    